#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, GAMEPLAY, BOSS, MAPTOOL, END };
	enum POSTEX_PATH {
		POSTEX_DEFAULT = 0,
		POSTEX_BLACKDISCARD,
		POSTEX_ALPHABLEND,
		POSTEX_ALPHABLEND_AND_COLOR,
		POSTEX_UI_BLEND,
		POSTEX_UI_BLEND_RIGHT,
		POSTEX_SOFTEFFECT,
		POSTEX_GRID_PICK,
		POSTEX_SOFTEFFECT_COLOR,
		POSTEX_PHASELOCK_DISTORT,

	};
	enum ANIMMESH_PATH {
		ANIMMESH_DEFAULT = 0,
		ANIMMESH_EMISSIVE,
		ANIMMESH_SHADOW
	};
	enum MESH_PATH {
		MESH_DEFAULT = 0,
		MESH_SKYDOME,
		MESH_EMISSIVE

	};

	enum class COL_GROUP { PLAYER, AR_BULLET, PST_BULLET, MONSTER, MON_ATTACK, MON_BULLET, BOSS, END };
	enum class COL_ID {
		PLAYER_BODY,
		PLAYER_HAND, // ?

		PLAYER_WEAPON_START,
		PLAYER_WEAPON_AR,
		PLAYER_WEAPON_PST,
		PLAYER_WEAPON_END,

		PLAYER_SKILL_PHASELOCK,

		MONSTER_START,
		MONSTER_RAKK,
		MONSTER_SKAG,
		MONSTER_SPIDERANT,
		MONSTER_BOSS_WARRIOR,
		MONSTER_BOSS_LEVIATHAN,
		MONSTER_BOSS_LEVIATHAN_HITMESH,
		MONSTER_END,


		MONSTER_HEAD_START,
		MONSTER_RAKK_HEAD,
		MONSTER_SKAG_HEAD,
		MONSTER_SPIDERANT_HEAD,
		MONSTER_BOSS_WARRIOR_HEAD,
		MONSTER_HEAD_END,

		MONSTER_ATK_START,
		MONSTER_RAKK_ATK,
		MONSTER_SKAG_ATK,
		MONSTER_SPIDERANT_ATK,
		MONSTER_BOSS_LEVIATHAN_ATK,
		MONSTER_ATK_END,

		MONSTER_BULLET_START,
		MONSTER_SPIDERANT_SPIT,
		MONSTER_BULLET_END,
		END
	};

#define CI_PLWEAPON( ID ) (COL_ID::PLAYER_WEAPON_START <= ID && ID <= COL_ID::PLAYER_WEAPON_END)
#define CI_MONSTER( ID ) (COL_ID::MONSTER_START <= ID && ID <= COL_ID::MONSTER_END)
#define CI_MONSTERHEAD( ID ) (COL_ID::MONSTER_HEAD_START <= ID && ID <= COL_ID::MONSTER_HEAD_END)
#define CI_MONSTERATK( ID ) (COL_ID::MONSTER_ATK_START <= ID && ID <= COL_ID::MONSTER_ATK_END)
#define CI_MONSTERBULLET( ID ) (COL_ID::MONSTER_BULLET_START <= ID && ID <= COL_ID::MONSTER_BULLET_END)

	enum class UI_DEPTH
	{
		UI_PRIORITY,


		UI_EFFECT,


		UI_DECO,


		UI_FONT,


		UI_BUTTON,


		UI_HUD_START,
		UI_HIT_SHIELD,
		UI_HIT_HP,
		UI_AIM,
		UI_HP_ICON,
		UI_HPBAR,
		UI_HP,
		UI_SHIELD_ICON,
		UI_SHIELDBAR,
		UI_SHIELD,
		UI_AMMO_ICON,
		UI_AMMOBAR, 
		UI_AMMO,
		UI_EXP_BAR,
		UI_EXP,
		UI_SKILL_BAR,
		UI_SKILL,
		UI_HUD_END,


		UI_PLAYER,


		UI_OBJECT_HUD,


		UI_BACKGROUND


	};

}