#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, GAMEPLAY, MAPTOOL, END };

	enum class COL_GROUP { PLAYER, AR_BULLET, PST_BULLET, MONSTER, BOSS, BULLET, END };
	enum class COL_ID {
		PLAYER_BODY,
		PLAYER_HAND,
		MONSTER_RAKK,
		MONSTER_RAKK_HEAD,
		BOSS_WARRIOR,
		BOSS_WARRIOR_HEAD,
		END
	};
}


